# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_b225de312b91645bcaf97c4a78976f139a6a2ba4

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

sonar.sources=\
client/src/components/,\
client/src/context/,\
client/src/hooks/useCategory.js,\
client/src/pages/,\
config/,\
controllers/,\
models/,\
helpers/,\
middlewares/,\

sonar.inclusions=**/*.js
sonar.exclusions=\
**/_site/**,\
**/__tests__/**,\
**/tests/**,\
**/mocks/**,\
**/__mocks__/**,\
**/*.test.js,\
**/*.spec.js,\
**/*.integration.test.js

sonar.javascript.lcov.reportPaths=coverage/merged.info

sonar.language=js
sonar.sourceEncoding=UTF-8